# Please refer to https://scipy.github.io/devdocs/building/index.html
# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate scipy-dev
#
name: scipy-dev
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - cython=3.0.2
  - compilers=1.6.0  # Currently unavailable for Windows. Comment out this line and download Rtools and add <path>\ucrt64\bin\ to your path: https://cran.r-project.org/bin/windows/Rtools/rtools40.html
  - meson=1.2.1
  - meson-python=0.13.2
  - ninja=1.11.1
  - numpy=1.25.2
  - openblas=0.3.23
  - pkg-config=0.29.2
  - libblas=*=*openblas  # helps avoid pulling in MKL
  - pybind11=2.11.1
  # scipy.datasets dependency
  - pooch=1.7.0
  # ---
  - pythran=0.13.1
  # For testing and benchmarking
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - pytest-xdist=3.3.1
  - pytest-timeout=2.1.0
  - asv=0.6.0
  - hypothesis=6.83.0
  # For type annotations
  - mypy=1.5.1
  - typing_extensions=4.7.1
  - types-psutil=5.9.5
  # For building docs
  - sphinx=5.3.0
  - numpydoc=1.5.0
  - ipython=8.14.0
  - setuptools=67.1.0 # avoid pkg_resources deprecation warnings from MPL/scikit-umfpack
  - matplotlib=3.7.2
  - pydata-sphinx-theme==0.9.0
  - sphinx-design=0.5.0
  - jupytext=1.15.1
  - myst-nb=0.17.2
  # Some optional test dependencies
  - mpmath=1.3.0
  - gmpy2=2.1.2
  - threadpoolctl=3.2.0
  # For CLI
  - rich-click=1.6.1
  - click=8.1.7
  - doit=0.36.0
  - pydevtool=0.3.0
  # For linting
  - ruff=0.0.286
  - cython-lint=0.15.0
